### ISSUE TITLE
Error when trying to profile_list

### ISSUE THREAD

**Issue by enewe101** [elric-dev/chirpy#1]
Running `chirpy profile_list` gave the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ndg/enewel3/.local/lib/python2.7/site-packages/chirpy/command_line.py", line 200, in <module>
    profileModule.plist(configs['lpath'], configs['ppath'])
  File "/home/ndg/enewel3/.local/lib/python2.7/site-packages/chirpy/profileModule.py", line 81, in plist
    p = a[0].rstrip()
IndexError: list index out of range
```

This is most likely because of running `chirpy profile_list` soon after initiating a `chirpy user` command: the `chirpy user` command had created a new log, but had not yet written anything to file.

Probable fix is to have the `profileModule.plist()` tolerate empty log files, or avoid letting log files be empty for any amount of time.

Calling `chirpy profile_list` a few minutes later worked (probably because the log file had content at that point).

**Comment by hmsaleem** [comment]
Thanks, will fix it in the next push along with unittests and any other bugs.
